import type { Metadata } from "next";
export const metadata: Metadata = { title: "Para directivos UDD" };
const mailto = "mailto:gagomez@udd.cl?subject=Conversaci%C3%B3n%20institucional%20sobre%20AssessTrace&body=Hola%20Germ%C3%A1n%3A%0A%0AMe%20gustar%C3%ADa%20conversar%20sobre%20una%20demostraci%C3%B3n%20o%20piloto%20de%20AssessTrace.%0A%0AUnidad%20o%20programa%3A%0AContexto%20de%20inter%C3%A9s%3A%0A%0ASaludos%2C";
export default function LeadershipPage() {
  return (
    <main id="contenido-principal">
      <section className="page-hero executive-hero"><div className="shell executive-grid"><div><p className="brand-kicker">Brief institucional</p><h1>La evaluación necesita nueva evidencia, no más vigilancia.</h1></div><p>AssessTrace ayuda a docentes y programas a rediseñar cómo observan el aprendizaje en cursos con IA, preservando autoridad académica y límites operativos explícitos.</p></div></section>
      <section className="section shell leadership-case"><div className="section-heading"><h2>La brecha que una buena entrega puede ocultar</h2><p>Un resultado final puede ser correcto sin demostrar comprensión individual, decisiones fundamentadas, iteración o verificación del uso de IA.</p></div><div className="decision-statement"><span>Pregunta institucional</span><strong>¿Qué evidencia necesita un curso para sostener que el aprendizaje ocurrió?</strong></div></section>
      <section className="section governance-section"><div className="shell"><div className="section-heading compact-heading"><h2>Gobernanza incorporada en el diseño</h2></div><div className="governance-table"><div><strong>Autoridad</strong><p>El docente confirma o modifica cada decisión material.</p></div><div><strong>Privacidad</strong><p>El flujo de rediseño excluye datos y trabajos de estudiantes.</p></div><div><strong>Seguridad</strong><p>Canvas es lectura por defecto; no existe comando de publicación o eliminación.</p></div><div><strong>Trazabilidad</strong><p>Fuentes, propuestas, decisiones y pendientes conservan roles distintos.</p></div></div></div></section>
      <section className="section shell pilot-section"><div className="pilot-copy"><h2>Un piloto pequeño antes de una promesa grande.</h2><p>Proponemos comenzar con dos o tres cursos, acompañados por diseño instruccional o dirección de programa, y revisar utilidad, carga, claridad y seguridad antes de ampliar.</p></div><ol className="pilot-steps"><li><span>1</span><div><strong>Seleccionar</strong><p>Cursos con distintas formas de evaluación y niveles de uso de IA.</p></div></li><li><span>2</span><div><strong>Rediseñar</strong><p>Documentar la situación inicial, decisiones y estructura propuesta.</p></div></li><li><span>3</span><div><strong>Evaluar</strong><p>Contrastar tiempo, valor pedagógico, adopción y condiciones de escalamiento.</p></div></li></ol></section>
      <section className="section trust-section executive-cta"><div className="shell trust-layout"><div><h2>AssessTrace no pide una decisión de adopción a ciegas.</h2><p>La siguiente conversación es una demostración con un caso sanitizado y una revisión conjunta de condiciones institucionales.</p></div><a className="button button-accent" href={mailto}>Solicitar demostración o piloto</a></div></section>
    </main>
  );
}
