import type { Metadata } from "next";
export const metadata: Metadata = { title: "Solicitar acceso" };
const accessMail = "mailto:gagomez@udd.cl?subject=Solicitud%20de%20acceso%20a%20AssessTrace&body=Hola%20Germ%C3%A1n%3A%0A%0AQuisiera%20solicitar%20acceso%20a%20AssessTrace.%0A%0AUsuario%20de%20GitHub%3A%0AInstituci%C3%B3n%20o%20unidad%3A%0ACurso%2C%20programa%20o%20contexto%20de%20uso%3A%0A%0A%C2%BFPor%20qu%C3%A9%20quiero%20utilizar%20AssessTrace%3F%0A%0A%C2%BFPara%20qu%C3%A9%20evaluaci%C3%B3n%2C%20curso%20o%20proyecto%20quiero%20utilizarlo%3F%0A%0AConfirmo%20que%20no%20incluir%C3%A9%20datos%20personales%20de%20estudiantes.%0A%0ASaludos%2C";
export default function AccessPage() {
  return (
    <main id="contenido-principal">
      <section className="page-hero access-hero"><div className="shell narrow-shell"><p className="brand-kicker dark-kicker">Acceso acompañado</p><h1>Cuéntanos por qué y para qué quieres usar AssessTrace.</h1><p>La web y el diagnóstico son públicos. El acceso operativo se autoriza mediante tu usuario de GitHub para acompañar el uso inicial y mantener una distribución controlada.</p><a className="button button-primary" href={accessMail}>Preparar solicitud por correo</a></div></section>
      <section className="section shell access-layout"><div><h2>Qué debe incluir tu correo</h2><ul className="check-list"><li>Tu nickname de GitHub.</li><li>Institución, unidad o programa.</li><li>Por qué quieres usar AssessTrace.</li><li>Para qué curso, evaluación o proyecto.</li><li>Confirmación de que no incluirás datos personales de estudiantes.</li></ul></div><div className="access-process"><span>Después de enviar</span><ol><li><strong>Revisión del contexto</strong><p>Confirmamos si el MVP se ajusta al uso propuesto.</p></li><li><strong>Autorización</strong><p>Recibes acceso e instrucciones de instalación.</p></li><li><strong>Primera experiencia</strong><p>Usas tu prompt inicial con el plugin y mantienes las decisiones pedagógicas.</p></li></ol></div></section>
      <section className="section faq-section"><div className="shell narrow-shell"><h2>Preguntas frecuentes</h2><details><summary>¿Necesito saber programar?</summary><p>No. El diagnóstico prepara el contexto y el trabajo ocurre como una conversación guiada en Codex. La instalación inicial puede requerir apoyo técnico.</p></details><details><summary>¿La web guarda mis respuestas?</summary><p>No. El diagnóstico se ejecuta en tu navegador y no envía sus respuestas a un servidor.</p></details><details><summary>¿Puedo ingresar trabajos o datos de estudiantes?</summary><p>No. AssessTrace necesita estructura del curso, resultados, evaluaciones y restricciones; no necesita expedientes individuales.</p></details><details><summary>¿AssessTrace publica cambios en Canvas?</summary><p>No. Las inspecciones y dry-runs no realizan mutaciones. La creación protegida produce estructuras no publicadas y requiere confirmación explícita.</p></details></div></section>
    </main>
  );
}
